kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: oes-analysis-for-elastic
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: oes-analysis-for-elastic
      count: 1
      initialDelay: 30s
      provider:
        opsmx:
          gateUrl: https://argoqa-helm.isd-dev.opsmx.net/
          application: prabhutest1
          user: admin
          lifetimeHours: 04
          threshold:
            pass: 80
            marginal: 60
          services:
          - logTemplateName: elastictemp1
            logScopeVariables: "kubernetes.pod_name"          
            baselineLogScope: ".*{{args.baseline-hash}}.*"
            canaryLogScope: ".*{{args.canary-hash}}.*"
