---
metadata:
  name: "testapp"
apiVersion: "argoproj.io/v1alpha1"
kind: "AnalysisTemplate"
spec:
  metrics:
  - provider:
      opsmx:
        canaryStartTime: "2022-09-26T04:17:00.002Z"
        application: "argoappqatestdestz"
        profile: "opsmx-profile"
        lifetimeMinutes: 6
        threshold:
          pass: 80
          marginal: 60
        services:
        - logTemplateName: "elk"
          metricTemplateName: "dd"
          metricScopeVariables: "app_key,pod_key"
          canaryMetricScope: "issugen-baseline,76f78f85ff"
          baselineMetricScope: "issugen-baseline,6944b5c7df"
        gateUrl: "https://isd-argocd.isd-dev.opsmx.net/gate/"
        user: "admin"
        baselineStartTime: "2022-09-26T04:17:00.002Z"
    name: "testapp"
